# Generated by Django 4.2.7 on 2024-02-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objective',
            name='estimated_hours',
            field=models.IntegerField(default=0, help_text='Estimated number of hours to complete the task'),
        ),
        migrations.AddField(
            model_name='objective',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
