# Generated by Django 4.2.7 on 2023-12-01 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objective', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectiveDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_draft', models.BooleanField(default=True)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objective.objective')),
            ],
        ),
    ]
