# Generated by Django 4.2.7 on 2023-11-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objective', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definitionofgood',
            name='objective_id',
        ),
    ]
