# Generated by Django 4.2.7 on 2023-11-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective', '0002_remove_definitionofgood_objective_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skills',
        ),
        migrations.AddField(
            model_name='team',
            name='skills',
            field=models.ManyToManyField(related_name='skills', through='objective.TeamSkill', to='objective.skill'),
        ),
    ]
