# Generated by Django 4.2.7 on 2023-12-12 08:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective', '0002_objectivedraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('number', models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), 'Amount must be a positive interger')])),
                ('unit', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='objective',
            name='kpis',
            field=models.ManyToManyField(blank=True, null=True, related_name='kpi_objectives', to='objective.kpi'),
        ),
    ]
