# Generated by Django 4.2.7 on 2024-01-29 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objective', '0003_alter_objective_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='objectives_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
