# Generated by Django 4.2.7 on 2023-12-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective', '0003_kpi_objective_kpis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='kpis',
        ),
        migrations.AddField(
            model_name='kpi',
            name='objectives',
            field=models.ManyToManyField(blank=True, null=True, related_name='objective_kpis', to='objective.objective'),
        ),
    ]
