# Generated by Django 4.2.7 on 2023-11-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective', '0003_remove_skill_skills_team_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='action_phrase',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='objective',
            name='repeat_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='objective',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
