# Generated by Django 4.2.7 on 2024-02-28 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objective', '0004_objective_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField()),
                ('goal_type', models.CharField(choices=[('Financial', 'Financial'), ('Non-Financial', 'Non-Financial')], max_length=300)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Intermediate', 'Intermediate'), ('High', 'High')], max_length=300)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('assign_to', models.ManyToManyField(blank=True, related_name='op_goal_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('visible_to', models.ManyToManyField(blank=True, related_name='op_goal_visible_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='objective',
            name='operational_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectives', to='objective.operationalgoal'),
        ),
    ]
