# Generated by Django 4.2.7 on 2024-01-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective', '0004_alter_objective_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='achievement_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
