# Generated by Django 4.2.7 on 2023-12-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objective', '0005_remove_kpi_objectives_kpi_objectives'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kpi',
            old_name='objectives',
            new_name='objective',
        ),
    ]
