# Generated by Django 4.2.7 on 2024-03-01 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objective', '0006_objectiveauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectiveauditlog',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives_changes', to='objective.objective'),
        ),
    ]
