# Generated by Django 4.2.7 on 2024-03-02 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objective', '0007_alter_objectiveauditlog_objective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='assign_to_to_id',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='assign_to_to_type',
        ),
    ]
