# Generated by Django 4.2.7 on 2024-03-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective', '0008_remove_objective_assign_to_to_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectivetool',
            name='objective_tool_id',
        ),
        migrations.AddField(
            model_name='objectivetool',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objective',
            name='end_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='objective_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='objective',
            name='start_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
