# Generated by Django 4.2.7 on 2024-01-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective', '0009_alter_team_created_by_userteam_team_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='repeat_date',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Weekly', max_length=100),
            preserve_default=False,
        ),
    ]
