# Generated by Django 4.2.7 on 2024-03-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective', '0009_remove_objectivetool_objective_tool_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectiveskill',
            name='objective_skill_id',
        ),
        migrations.AddField(
            model_name='objectiveskill',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
