# Generated by Django 3.2.9 on 2024-01-19 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objective', '0011_alter_objective_repeat_date'),
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='objective',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='objective.objective'),
        ),
    ]
