# Generated by Django 4.2.7 on 2024-02-26 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objective', '0002_objective_completion_date_objective_estimated_hours_and_more'),
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionMainEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('what_you_did_today', models.TextField()),
                ('duration', models.IntegerField(null=True)),
                ('achievements', models.CharField(choices=[('Learnings', 'Learnings'), ('Deliverable', 'Deliverable'), ('Work-Product', 'Work-Product'), ('innovation', 'innovation'), ('Miscellaneous', 'Miscellaneous')], default='Learnings', max_length=20)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_entry', to='objective.objective')),
            ],
        ),
    ]
