# Generated by Django 4.2.7 on 2024-02-26 23:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('action', '0002_actionmainentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionmainentry',
            name='collaborators',
            field=models.ManyToManyField(related_name='action_main_entry_collaborators', to=settings.AUTH_USER_MODEL),
        ),
    ]
