# Generated by Django 4.2.7 on 2024-03-01 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('action', '0004_alter_actionmainentry_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionmainentry',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_main_entry_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
