# Generated by Django 4.2.7 on 2024-03-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective', '0007_alter_objectiveauditlog_objective'),
        ('action', '0005_alter_actionmainentry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionmainentry',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='action_main_entry_skills', to='objective.skill'),
        ),
        migrations.AddField(
            model_name='actionmainentry',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='action_main_entry_tools', to='objective.tool'),
        ),
    ]
