# Generated by Django 4.2.7 on 2024-03-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0006_actionmainentry_skills_actionmainentry_tools'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionmainentry',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Validated', 'Validated'), ('Rejected', 'Rejected')], default='Pending', max_length=300),
        ),
    ]
