# Generated by Django 4.2.7 on 2024-03-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0008_actionmainentry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionmainentry',
            name='date',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
